import { animationParams } from "./animationParams.js";

/** @type {Record<string, Partial<typeof animationParams>>} */
export const ANIMATION_PRESETS = {
  breathing: {
    playing: true,
    motionType: "sine",
    amplitude: 0.08,
    frequency: 0.28,
    speed: 0.35,
    phaseSpread: 0.35,
    randomness: 0.12,
    axisX: 0.15,
    axisY: 1,
    axisZ: 0.1,
    selectionMode: "all",
    phaseMode: "index",
    radialBias: 0.8,
    heightBias: 0.5,
  },
  tectonic: {
    playing: true,
    motionType: "tectonic",
    amplitude: 0.14,
    frequency: 0.22,
    speed: 0.4,
    phaseSpread: 0.7,
    randomness: 0.35,
    axisX: 1,
    axisY: 0.2,
    axisZ: 1,
    selectionMode: "outsideToInside",
    percentage: 65,
    phaseMode: "radial",
    radialBias: 1.2,
    heightBias: 0.3,
  },
  collapse: {
    playing: true,
    motionType: "dissolve",
    amplitude: 0.22,
    frequency: 0.18,
    speed: 0.55,
    phaseSpread: 0.9,
    randomness: 0.2,
    axisX: 0.5,
    axisY: 1,
    axisZ: 0.5,
    selectionMode: "insideToOutside",
    percentage: 80,
    phaseMode: "height",
    radialBias: 0.6,
    heightBias: 1.4,
  },
  floatingInk: {
    playing: true,
    motionType: "noiseOscillation",
    amplitude: 0.1,
    frequency: 0.4,
    speed: 0.5,
    phaseSpread: 1.1,
    randomness: 0.55,
    axisX: 0.6,
    axisY: 0.85,
    axisZ: 0.45,
    selectionMode: "random",
    percentage: 72,
    phaseMode: "random",
    radialBias: 1,
    heightBias: 0.8,
  },
  harmonicResonance: {
    playing: true,
    motionType: "harmonic",
    amplitude: 0.11,
    frequency: 0.45,
    speed: 0.48,
    phaseSpread: 0.5,
    randomness: 0.18,
    axisX: 0.4,
    axisY: 1,
    axisZ: 0.35,
    selectionMode: "everyNth",
    nthStep: 2,
    phaseMode: "height",
    radialBias: 0.9,
    heightBias: 1.1,
  },
};

export function applyPreset(name) {
  const preset = ANIMATION_PRESETS[name];
  if (!preset) return;
  Object.assign(animationParams, preset);
}
